# docker-compose.yml
version: '3.1'
services:
  prometheus:
    build:
      context: ../
      dockerfile: docker/prometheus/dockerfile
    container_name: "prometheus"
    hostname: "prometheus"
    ports:
      - "9090:9090"
    links:
      - axonserver-enterprise-1
      - axonserver-enterprise-2
      - axonserver-enterprise-3
    networks:
      - axon-net

  grafana:
    build:
      context: ../
      dockerfile: docker/grafana/dockerfile
    image: grafana/grafana
    container_name: "grafana"
    hostname: "grafana"
    ports:
      - "3000:3000"
    links:
      - prometheus
    networks:
      - axon-net

  demo-app-1:
    image:  demo-app:0.1.0-SNAPSHOT
    depends_on:
      - axonserver-enterprise-1
      - axonserver-enterprise-2
      - axonserver-enterprise-3
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver-enterprise-1:8124,axonserver-enterprise-2:8125,axonserver-enterprise-3:8126
      - SERVER_PORT=8080
      - MANAGEMENT_SERVER_PORT=8081
    links:
      - axonserver-enterprise-1
      - axonserver-enterprise-2
      - axonserver-enterprise-3
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - axon-net


  demo-app-2:
    image: demo-app:0.1.0-SNAPSHOT
    depends_on:
      - axonserver-enterprise-1
      - axonserver-enterprise-2
      - axonserver-enterprise-3
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver-enterprise-1:8124,axonserver-enterprise-2:8125,axonserver-enterprise-3:8126
      - SERVER_PORT=8082
      - MANAGEMENT_SERVER_PORT=8083
    links:
      - axonserver-enterprise-1
      - axonserver-enterprise-2
      - axonserver-enterprise-3
    ports:
      - 8082:8082
      - 8083:8083
    networks:
      - axon-net

  axonserver-enterprise-1:
    image: axonserver-enterprise:4.5.1
    build:
      context: ./axon-server
      dockerfile: dockerfile
    hostname: axonserver-enterprise-1
    environment:
      - AXONIQ_AXONSERVER_CLUSTERTEMPLATE_PATH=/axonserver/cluster-template.yml
      - AXONIQ_LICENSE=/axonserver/axoniq.license
      - SERVER_PORT=8024
      - AXONIQ_AXONSERVER_PORT=8124
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUS-ENABLED=true
    volumes:
      - axonserver-enterprise-1-log:/axonserver/log
      - axonserver-enterprise-1-events:/axonserver/events
      - axonserver-enterprise-1-data:/axonserver/data
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-net

  axonserver-enterprise-2:
    image: axonserver-enterprise:4.5.1
    build:
      context: ./axon-server
      dockerfile: dockerfile
    hostname: axonserver-enterprise-2
    environment:
      - AXONIQ_AXONSERVER_CLUSTERTEMPLATE_PATH=/axonserver/cluster-template.yml
      - AXONIQ_LICENSE=/axonserver/axoniq.license
      - SERVER_PORT=8025
      - AXONIQ_AXONSERVER_PORT=8125
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUS-ENABLED=true
    volumes:
      - axonserver-enterprise-2-log:/axonserver/log
      - axonserver-enterprise-2-events:/axonserver/events
      - axonserver-enterprise-2-data:/axonserver/data
    ports:
      - '8025:8025'
      - '8125:8125'
      - '8225:8225'
    networks:
      - axon-net

  axonserver-enterprise-3:
    image: axonserver-enterprise:4.5.1
    build:
      context: ./axon-server
      dockerfile: dockerfile
    hostname: axonserver-enterprise-3
    environment:
      - AXONIQ_AXONSERVER_CLUSTERTEMPLATE_PATH=/axonserver/cluster-template.yml
      - AXONIQ_LICENSE=/axonserver/axoniq.license
      - SERVER_PORT=8026
      - AXONIQ_AXONSERVER_PORT=8126
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUS-ENABLED=true
    volumes:
      - axonserver-enterprise-3-log:/axonserver/log
      - axonserver-enterprise-3-events:/axonserver/events
      - axonserver-enterprise-3-data:/axonserver/data
    ports:
      - '8026:8026'
      - '8126:8126'
      - '8226:8226'
    networks:
      - axon-net


volumes:
  axonserver-enterprise-1-log:
  axonserver-enterprise-1-events:
  axonserver-enterprise-1-data:
  axonserver-enterprise-2-log:
  axonserver-enterprise-2-events:
  axonserver-enterprise-2-data:
  axonserver-enterprise-3-log:
  axonserver-enterprise-3-events:
  axonserver-enterprise-3-data:

networks:
  axon-net: