FROM openjdk:8-jre-alpine3.9

RUN apk add --update ttf-dejavu fontconfig

COPY axonserver.jar /axonserver/axonserver-enterprise.jar
COPY axoniq.license /axonserver/axoniq.license
COPY cluster-template.yml /axonserver/cluster-template.yml
COPY axonserver.properties /axonserver/axonserver.properties

WORKDIR /axonserver

CMD ["java", "-jar", "/axonserver/axonserver-enterprise.jar"]